github: [alex-spataru]
custom:
  - [Donate via PayPal](https://www.paypal.com/donate?hosted_button_id=XN68J47QJKYDE)
  - [Purchase Serial Studio Pro](https://store.serial-studio.com/buy/ba46c099-0d51-4d98-9154-6be5c35bc1ec)
